#!/usr/bin/python3
#define constants used to exchange with dbus
ADAPTER_NAME = "hci0"
DBUS_PROPERTIES="org.freedesktop.DBus.Properties"
DBUS_OM_IFACE = 'org.freedesktop.DBus.ObjectManager'

#define constants used to communicate with bluez
BLUEZ_SERVICE_NAME = "org.bluez"
BLUEZ_NAMESPACE = "/org/bluez/"
ADAPTER_INTERFACE = BLUEZ_SERVICE_NAME + ".Adapter1"
DEVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".Device1"
GATT_MANAGER_INTERFACE = BLUEZ_SERVICE_NAME + ".GattManager1"
GATT_SERVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".GattService1"
GATT_CHARACTERISTIC_INTERFACE = BLUEZ_SERVICE_NAME + ".GattCharacteristic1"
GATT_DESCRIPTOR_INTERFACE = BLUEZ_SERVICE_NAME + ".GattDescriptor1"
MEDIAENDPOINT_SERVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".MediaEndpoint1"
MEDIATRANSPORT_CHARACTERISTIC_INTERFACE = BLUEZ_SERVICE_NAME + ".MediaTransport1"
MEDIAPLAYER_SERVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".MediaPlayer1"
NETWORK_SERVICE_INTERFACE = BLUEZ_SERVICE_NAME + ".Network1"
MEDIAPLAYER_CHARACTERISTIC_INTERFACE = BLUEZ_SERVICE_NAME + ".MediaItem1"

#error codes
RESULT_OK = 0
RESULT_ERR = 1
RESULT_ERR_NOT_CONNECTED = 2
RESULT_ERR_NOT_SUPPORTED = 3
RESULT_ERR_SERVICES_NOT_RESOLVED = 4	
RESULT_ERR_WRONG_STATE = 5
RESULT_ERR_ACCESS_DENIED = 6
RESULT_EXCEPTION = 7
RESULT_ERR_BAD_ARGS = 8
RESULT_ERR_NOT_FOUND = 9

#identify BLE services and characteristics of ECCEL rfid reader
ECCEL_READ_CHARACTERISTIC_UUID =  "f03c26b3-3fb1-4d67-912e-4ae31159aef0"
ECCEL_WRITE_CHARACTERISTIC_UUID = "f03c26b2-3fb1-4d67-912e-4ae31159aef0"
ECCEL_SERVICE_UUID = "f03c26b1-3fb1-4d67-912e-4ae31159aef0"
