FROM guepydocker/rpinodered

WORKDIR /usr/src/node-red
COPY --chown=node-red:node-red ../../nfs_rfidproject/volumes/rpinodered/_data/package.json .
COPY --chown=node-red:node-red ../../nfs_rfidproject/volumes/rpinodered/_data/flows.json /data/
COPY --chown=node-red:node-red ../../nfs_rfidproject/volumes/rpinodered/_data/setting.js /data/
COPY --chown=node-red:node-red ../..//nfs_rfidproject/volumes/rpinodered/_data/tcp_client_file.py /data/
COPY --chown=node-red:node-red ../..//nfs_rfidproject/volumes/rpinodered/_data/chat_tcp_server.py /data/

RUN npm install --unsafe-perm --no-update-notifier --no-audit \
				--only=production

USER node-red
CMD ["npm", "start"]
