FROM guepydocker/ble_app_img_no_ufs

USER root
WORKDIR /home/$USERNAME
RUN pip3 install pyyaml
RUN mkdir -p ./Documents/pyBLuez
WORKDIR /home/$USERNAME/Documents/pyBLuez
COPY --chown=$USERNAME:$USERNAME ~/rfidproject/pyBLuez/ .
RUN chmod +x ./entrypoint.sh
ENTRYPOINT ["./entrypoint.sh"]
