version: '3'

services:
  ble_app:
    build: 
      context: .
      dockerfile: Dockerfile_bleapp_ufs
    container_name: ble
    network_mode: "host"
    privileged: true
    user: root
    volumes:
      - type: bind
        source: /run/dbus/system_bus_socket
        target: /run/dbus/system_bus_socket

  
